name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby-9.4.6.0
          bundler-cache: true
      - name: Test with JRuby
        run: |
          jruby -S bundle install
          jruby -S bundle exec rspec
          
